#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # runfunctions
postProcess -func grad(U)
simpleFoam -postProcess -func R 
postProcess -func sample
postProcess -func sample_surf
